name: SAST

on: [push, pull_request]

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 安裝 Semgrep
      - name: Install Semgrep
        run: |
          pip install semgrep
      
      # 執行掃描
      - name: Run Semgrep
        run: semgrep --config=semgrep-rules.yml .
